spring:
  application:
    name: sunboat-user

# Nacos registry + Dubbo configuration (example defaults: nacos://127.0.0.1:8848, Dubbo 20880)
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
    group: dev
  protocol:
    name: dubbo
    port: 20881


#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://127.0.0.1:8848  # Nacos注册中心地址
#  protocol:
#    name: dubbo
#    port: -1  # 随机端口
#
## Nacos配置中心配置
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848  # Nacos服务器地址
#    namespace: dev  # 命名空间，默认public
#    group: USER_GROUP  # 配置分组
#    file-extension: yaml  # 配置文件格式
#    refresh-enabled: true  # 开启动态刷新